# Model Configuration
PConfig:
    config_fpath: _configs_models/
    model: Grape_ColdHardiness_TensorBatch #Suffixes: Batch, BatchFast
    model_parameters: grape_coldhardiness:1
    latitude: 44
    longitude: -123
    start_date: 1990-09-07
    input_vars: [DAY, TEMP, TMIN, TMAX, RAIN, IRRAD, LAT, LON, ET0, E0, ES0]
    output_vars: [LTE50]
log_path: /_data/
run_name: synth_data
seed: 0
cultivar: Barbera
withold_cultivars: {}
data_fpath: _data/processed_data/
val_set: True
params: ["TBASEM"]
params_range: [[0,15]]
# DConfig Parameters
DConfig: 
    arch: FCGRU
    hidden_dim: 128
    loss_func: MSELoss
    learning_rate: .001
    lr_factor: 0.9
    batch_size: 1
    epochs: 600
